name: Seasoning-E-Commerce
fileGroups:
  - configs
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  Seasoning-E-Commerce:
    type: application
    platform: iOS
    sources: Seasoning-E-Commerce
    settings:
      CURRENT_PROJECT_VERSION: "1"
      INFOPLIST_FILE: Seasoning-E-Commerce/info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.g4zeru.Seasoning-E-Commerce
      DEVELOPMENT_TEAM: 8446Z6F5D6
      SWIFT_VERSION: "5.0"
      IPHONEOS_DEPLOYMENT_TARGET: "12.0"
    scheme:
      testTargets:
        - Seasoning-E-CommerceTests
  Seasoning-E-CommerceTests:
    type: bundle.unit-test
    platform: iOS
    sources: Seasoning-E-CommerceTests
    dependencies:
      - target: Seasoning-E-Commerce