name: TegakiMarche
fileGroups:
  - configs
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  TegakiMarche:
    type: application
    platform: iOS
    sources: TegakiMarche
    settings:
      CURRENT_PROJECT_VERSION: "1"
      INFOPLIST_FILE: TegakiMarche/info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.terany.TegakiMarche
      DEVELOPMENT_TEAM: 8446Z6F5D6
      SWIFT_VERSION: "5.0"
      IPHONEOS_DEPLOYMENT_TARGET: "12.0"
    scheme:
      testTargets:
        - TegakiMarcheTests
  TegakiMarcheTests:
    type: bundle.unit-test
    platform: iOS
    sources: TegakiMarcheTests
    dependencies:
      - target: TegakiMarche